### ISSUE TITLE
Don't work dev mode

### ISSUE THREAD

**Issue by Valexr** [nobkd/nue-editor#1]
`bun run dev` 

![Screenshot 2024-11-20 at 10 00 18](https://github.com/user-attachments/assets/1851e1c3-667b-40ad-bde8-a502cd5eedd3)

**Comment by nobkd** [comment]
Sorry, but I can't reproduce this. Did `nue` log errors?

Did the server maybe not start on `8888`?
Did you run `nue` dev server beforehand, maybe with the `prod.yaml` env file?

This would be really interesting, if there was such a case, that a file was missing from generation...

**Comment by Valexr** [comment]
Now I can’t reproduce too 😁 dev mode working 🤷🏻‍♂️

**Comment by nobkd** [comment]
okay... that's a bit bad... did you remove the `.dist` dir sometime after the failure?

**Comment by Valexr** [comment]
yep

**Comment by nobkd** [comment]
Maybe something broke somewhere in that directory...

Might be relevant, if this happens again...
